source.. = src/
output.. = bin/
bin.includes = META-INF/,\
			   .,\
			   OSGI-INF/org.nsoft.workflow.activities.MyActivator.xml,\
			   OSGI-INF/org.nsoft.workflow.activities.factory.NSoftFormFactory.xml,\	    
			   .
